export const ActionTypes = {
  GET_LIST_EMPLOYEE_REQUEST: "GET_LIST_EMPLOYEE_REQUEST",
  GET_LIST_EMPLOYEE_SUCCESS: "GET_LIST_EMPLOYEE_SUCCESS",
  GET_LIST_LOCATION: "GET_LIST_LOCATION",
  GET_LIST_LOCATION_SUCCESS: "GET_LIST_LOCATION_SUCCESS",
  GET_OTHER_FEATURE_SUCCESS: "GET_OTHER_FEATURE_SUCCESS",
  GET_OTHER_FEATURE: "GET_OTHER_FEATURE",
};
